config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :cards

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    def index
        @cards = Card.all
      end
    def show
        @card = Card.find(params[:id])
    end

    def new
        @card = Card.new
    end

    def edit
        @card = Card.find(params[:id])
    end

    def create
        @card = Card.new(card_params)
       
        if @card.save
            redirect_to cards_path
        else
            render 'new'
        end
    end


    def update
        @card = Card.find(params[:id])

        if @card.update(card_params)
            redirect_to @card
        else
            render 'edit'
        end
    end

    def destroy
        @card = Card.find(params[:id])
        @card.destroy
        
        redirect_to cards_path
    end

    private
        def card_params
            params.require(:card).permit(:name, :hp)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/edit.html.erb
<h1>Editing card</h1>
 
<%= form_for :card, url: card_path(@card), method: :patch do |f| %>
 
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited
        this card from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :hp %><br>
    <%= f.text_field :hp %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>HP</th>
  </tr>
    <%= link_to 'New card', new_card_path %>
  <% @cards.each do |card| %>
    <tr>
      <td><%= card.name %></td>
      <td><%= card.hp %></td>
      <td><%= link_to 'Show', card_path(card) %></td>
      <td><%= link_to 'Edit', edit_card_path(card) %></td>
    </tr>
  <% end %>
</table>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= form_for :card, url: cards_path do |f| %>

<% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited
        this card from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
   
    <p>
      <%= f.label :hp %><br>
      <%= f.text_field :hp %>
    </p>
   
    <p>
      <%= f.submit %>
    </p>
  <% end %>

app/views/cards/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>
 
<p>
  <strong>HP:</strong>
  <%= @card.hp %>
</p>
<ul>
<li><%= link_to 'Edit', edit_card_path(@card) %></li>
<li><%= link_to 'Back to List', cards_path %></li>
<li><%= button_to "Destroy", card_path(@card),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cards (Rails)</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>Hello Rails!</p>